import {randomUUID} from 'node:crypto';
import {db,migrate,now,production} from '../server/db.js';
import {passwordHash} from '../server/auth.js';
if(production)throw new Error('Demo seeding is disabled in production.');
await migrate();
if(await db('users').first()){console.log('Existing database found; seed skipped.');await db.destroy();process.exit(0);}
const admin=randomUUID(),tester=randomUUID(),other=randomUUID(),project=randomUUID(),project2=randomUUID();
await db.transaction(async q=>{
for(const u of [{id:admin,email:'admin@helm.local',name:'Alex Morgan',role:'admin'},{id:tester,email:'tester@helm.local',name:'Jamie Chen',role:'tester'},{id:other,email:'other@helm.local',name:'Riley Parker',role:'tester'}])await q('users').insert({...u,password_hash:passwordHash('Helm-local-2026!'),verified:true,active:true,created_at:now()});
await q('projects').insert([{id:project,name:'Helm Platform',description:'Core web experience',active:true,created_at:now()},{id:project2,name:'Glentree',description:'Glentree workspace',active:true,created_at:now()}]);for(const user_id of [tester,other])for(const project_id of [project,project2])await q('memberships').insert({user_id,project_id});
const items=[['Export button does not respond on Safari','Bug','In Progress','High','High','Billing','The export button appears clickable but no file downloads on Safari 18. The same export works in Chrome.'],['Add a date range filter to analytics','Improvement','Under Review','Low','Medium','Analytics','A custom date range would make it easier to compare campaign performance across weeks.'],['Profile photo appears stretched on mobile','Bug','Ready for Retest','Medium','Medium','Account','Profile images lose their original aspect ratio on smaller screens.'],['Invite email link expires too quickly','Bug','New','High','High','Workspace','Some testers cannot accept their invitation after opening it the next morning.'],['Remember the last selected workspace','Improvement','New','Low','Low','Workspace','Returning users would save time if the app opened their most recently used workspace.'],['Search returns archived projects','Bug','Reopened','Medium','Medium','Search','Archived projects still appear in the project switcher search results.'],['Keyboard focus disappears in settings','Bug','Closed','Medium','High','Accessibility','Keyboard navigation loses its visible focus indicator when entering the settings panel.'],['Add a compact view for issue lists','Improvement','Deferred','Low','Low','Dashboard','A compact list would help us review more issues on smaller laptop screens.']];
for(let n=0;n<items.length;n++){const [title,type,status,severity,priority,category,description]=items[n];const id=randomUUID();const date=new Date(Date.now()-(n+1)*20*3600000).toISOString();const [i]=await q('issues').insert({id,project_id:n%3===0?project2:project,reporter_id:n===5?other:tester,type,title,status,severity,priority,category,description,steps:type==='Bug'?'1. Open the affected page.\n2. Perform the described action.\n3. Observe the result.':'',expected:'The action should complete correctly.',actual:description,reason:type==='Improvement'?description:'',desired:type==='Improvement'?'A simpler and more predictable experience.':'',notes:'',url:'',environment:'staging',build:'v2.4.0',device:'Safari · macOS',created_at:date,updated_at:date,idempotency_key:randomUUID(),cycle:status==='Ready for Retest'?1:0}).returning('*');await q('issues').where({id}).update({reference:`${type==='Bug'?'BUG':'IMP'}-${String(i.number).padStart(6,'0')}`});await q('activity').insert({id:randomUUID(),issue_id:id,user_id:tester,action:'Submitted',detail:'Issue reported with reproduction details.',internal:false,created_at:date});if(status==='Ready for Retest')await q('approvals').insert({id:randomUUID(),issue_id:id,admin_id:admin,cycle:1,summary:'Profile photos now preserve their original aspect ratio across screen sizes.',build:'v2.4.1',test_url:'',created_at:date});}
});
console.log('Local demo seeded. Admin: admin@helm.local; tester: tester@helm.local; password: Helm-local-2026!');await db.destroy();
